Improve realpath
- OCaml 4.13 ships realpath on Unix and Windows. Offload
  core_unix_realpath to caml_unix_realpath if OCaml >= 4.13 is used.

- realpath(..., NULL) allocating a buffer is POSIX 2008. There are no
  more common systems that don't implement this feature. The OCaml
  4.13 implementation uses it inconditonaly. It shouldn't be
  restricted to glibc (musl, BSDs, macOS support it).

- add a fallback if realpath isn't implemented (e.g., on Windows,
  before OCaml 4.13).

This also fixes the following warning:

    filename_unix_stubs.c:31:9: warning: initializing 'char *' with an expression of type 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
       31 |   char *path = String_val(v_path);
          |         ^      ~~~~~~~~~~~~~~~~~~
    1 warning generated.

and makes realpath available on Windows (the following was reported by
MinGW-w64):

    In file included from C:\Users\opam\AppData\Local\opam\5.3\lib\jane-street-headers/ocaml_utils.h:6,
                     from filename_unix_stubs.c:5:
    filename_unix_stubs.c: In function 'core_unix_realpath':
    C:/Users/opam/AppData/Local/opam/5.3/lib/ocaml/caml/mlvalues.h:365:23: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
      365 | #define String_val(x) ((const char *) Bp_val(x))
          |                       ^
    filename_unix_stubs.c:31:16: note: in expansion of macro 'String_val'
       31 |   char *path = String_val(v_path);
          |                ^~~~~~~~~~
    filename_unix_stubs.c:36:7: warning: implicit declaration of function 'realpath' [-Wimplicit-function-declaration]
       36 |   if (realpath(path, resolved_path) == NULL)
          |       ^~~~~~~~
    filename_unix_stubs.c:36:37: warning: comparison between pointer and integer
       36 |   if (realpath(path, resolved_path) == NULL)
          |                                     ^~

Signed-off-by: Antonin Décimo <antonin@tarides.com>