strerror_s is missing on Windows, but strerror is thread-safe
    error_checking_mutex_stubs.c: In function 'caml_pthread_check':
    error_checking_mutex_stubs.c:23:7: warning: implicit declaration of function 'strerror_r'; did you mean 'strerror_s'? [-Wimplicit-function-declaration]
       23 |   if (strerror_r(retcode, err_buf, err_buf_len) == -1)
          |       ^~~~~~~~~~
          |       strerror_s

Signed-off-by: Antonin Décimo <antonin@tarides.com>